### ISSUE TITLE
[Bug Report] Max RSS is Significantly Higher in Version 2.0

### ISSUE THREAD

**Issue by jordanstephens** [Shopify/packwerk#164]
**Description**
Memory usage in packwerk v2.0 is significantly higher than it was in v1.4—so much higher that we will need to increase the resource class of our CI nodes in order for us to run packwerk v2.0. It looks like the max RSS for the whole process tree has increased from ~850 MB to about ~2.5GB for our use-case.

I ran gnu `time -v` on `bin/packwerk check` in our application working directory using both versions of packwerk and saw the following results:

<table>
<tr>
	<td>Version 1.4</td>
	<td>Version 2.0</td>
</tr>
<tr>
    <td>

> Command being timed: "bin/packwerk check"
> User time (seconds): 79.86
> System time (seconds): 12.22
> Percent of CPU this job got: 719%
> Elapsed (wall clock) time (h:mm:ss or m:ss): 0:12.79
> Average shared text size (kbytes): 0
> Average unshared data size (kbytes): 0
> Average stack size (kbytes): 0
> Average total size (kbytes): 0
> **Maximum resident set size (kbytes): 83560**
> **Average resident set size (kbytes): 0**
> Major (requiring I/O) page faults: 0
> Minor (reclaiming a frame) page faults: 399579
> Voluntary context switches: 10258
> Involuntary context switches: 179007
> Swaps: 0
> File system inputs: 0
> File system outputs: 0
> Socket messages sent: 0
> Socket messages received: 0
> Signals delivered: 36
> Page size (bytes): 4096
> Exit status: 0

</td>
<td>

> Command being timed: "bin/packwerk check"
> User time (seconds): 81.06
> System time (seconds): 11.77
> Percent of CPU this job got: 381%
> Elapsed (wall clock) time (h:mm:ss or m:ss): 0:24.34
> Average shared text size (kbytes): 0
> Average unshared data size (kbytes): 0
> Average stack size (kbytes): 0
> Average total size (kbytes): 0
> **Maximum resident set size (kbytes): 334968**
> **Average resident set size (kbytes): 0**
> Major (requiring I/O) page faults: 5862
> Minor (reclaiming a frame) page faults: 1233804
> Voluntary context switches: 35237
> Involuntary context switches: 156020
> Swaps: 0
> File system inputs: 0
> File system outputs: 0
> Socket messages sent: 16
> Socket messages received: 16
> Signals delivered: 40
> Page size (bytes): 4096
> Exit status: 0
</td>
</table>

**To Reproduce**
Run packwerk while watching memory usage, compare between v1.4 and v2.0

**Expected Behaviour**
I expected memory usage to not increase so dramatically between v1.4 and v2.0.

**Screenshots**

The GNU time output only captures the max RSS of the root process, so I grabbed a couple screenshots from activity monitor to demonstrate that the memory usage is much higher in each of the child processes as well.

Packwerk v1.4 Memory Usage
<img width="875" alt="packwerk-v1 4-memory-usage" src="https://user-images.githubusercontent.com/706922/145480577-cbb97cd7-46b7-49af-b4de-f488dfb71d0c.png">

Packwerk v2.0 Memory Usage
<img width="873" alt="packwerk-v2 0-memory-usage" src="https://user-images.githubusercontent.com/706922/145479463-90d6edee-b108-42eb-98b5-2ce9f4160194.png">

**Version Information**
 - Packwerk: v2.0
 - Ruby v3.0.2

**Additional Context**

I haven't looked into the changes yet, but I assume this is because packwerk now loads our rails application in each of its processes? I still wouldn't expect each child process's max RSS to balloon up so much.

Do you all have any idea why this might be? And secondly, any idea if it would be possible and reasonable to bring this number back down?

Thanks!

**Comment by ngan** [comment]
I'm guessing this make sense and it sort of expected.

https://github.com/Shopify/packwerk/blob/4da4215cb9d15aeb8020a6324edc014c6094c50a/lib/packwerk/parse_run.rb#L74

`Parallel` will default to forking by the cpu count. And since we're in a context of the Rails application, it'll multiply the memory footprint dramatically (depending on the number of CPUs you have).

Off the top of my head, I can see 2 ways of resolving this issue: (1) switch to threads, or (2) load the rails environment only to extract the information we need. I'll outline the choices below:

### Switch to threads

Switching to threads is a little tricky because we'll have to deal with thread issues. It's not too bad since we're not actually serving requests or anything complicated (other than loading the app), the only threading issue we'll need to deal with is auto loading. We're at the mercy of the application on what it does in the `test` environment (whether or not it eager loads). A solution would be to eager load the app (`Rails.application.eager_load!`) right before we do the `Parallel.flat_map` call. I tried this and it works. However, the performance is not as good as forking. For some data, our monolith (37946 files scanned) does the check in `37.57 seconds` using forks, and `222.46 seconds` using threads (6x slower!). It solves the memory issue and we might be able to investigate the performance difference separately.

### Load rails and extract what we need

We could boot the rails app and dump (or however we want to communicate between the rails app and the check process) what we need. Eg load paths, inflections, etc. This allows us to stay with forks, still utilize spring to boot the application, keep the packwerk scanner process memory low.

**Comment by exterm** [comment]
Thank you for reporting this, Jordan, and for your analysis, Ngan.

When @AlexEvanczuk and I discussed this change, we didn't measure memory usage, only run time.

As an added data point, I just checked memory usage on our monolith and it doesn't seem to have increased substantially with packwerk 2.0.0. However, we were already using a springified binstub with packwerk 1.4, and if I disable spring on 1.4 I get significantly lower memory usage, comparable to the difference that Jordan is reporting.

It's an interesting problem, since we should _in theory_ only need to load a small part of the application to get the load paths, but in practice, we can't really know which part that is.

@ngan , why do you think we need to eager load the app? I would assume that loading the bundle and executing the initializers should be enough to initialize load paths & inflections.

**Comment by exterm** [comment]
> secondly, any idea if it would be possible and reasonable to bring this number back down?

@jordanstephens two workarounds come to mind for a short-term solution:

- revert to packwerk 1.4.0, currently there are no differences in behavior
- reduce parallelism; trade execution time for memory usage.

I haven't made up my mind on what the longer term course of action should be. Personally, I think the reduced complexity from removing the application caches may be worth the added memory usage - we're trading human effort for machine effort.

**Comment by exterm** [comment]
> What's the urgency of this problem for you all?

At Shopify, I have not heard any complaints about the increased memory usage.

In terms of solutions, I've just started looking into this, but the increased start up time from #166 has me concerned.

Having a separate process that doesn't load the whole bundle seems interesting. I'm also wondering if we can get a speedup by not loading anything in the `development` and `test` groups except packwerk - the application should be bootable without those things, and I'm curious what kind of speedup / memory usage reduction that would result in. I'm not super optimistic though because it's not a large part of the bundle.

**Comment by jordanstephens** [comment]
I haven't had a chance to look at the proposals yet, but I can say that we were able to work around the issue by reducing parallelism for now, but I would still like to see this improved. 

I think booting rails in a side process and sending the load paths back to the main process before the fork sounds like a good implementation to me, but I need to look into it more closely. From a high level, though, I would support pursuing a more optimal solution over thrashing through a short-term fix.

**Comment by AlexEvanczuk** [comment]
Hey all -- hope your holiday season was relaxing and safe.

Can you please share with me some of your thoughts on the tradeoffs that are important to you? My understanding right now is that we're trading off machine time/resources for human time, and that we may be okay with that tradeoff. Let me know how you feel.

If we wanted to not have this tradeoff, a medium term solution might involve packwerk commands loading rails and getting what we need, then running the rest of packwerk in an independent process that is given the rails dependencies. I see that as very similar to the previous proposal, except reversed (instead of rails dependencies being a separate process, packwerk is). Both of these solutions add a lot of complexity to the implementation, so our preference may be to wait until a longer-term solution. My ideal for a longer-term solution would be to see if we can use a non-zeitwerk based parser for Packwerk. @exterm did some investigation on that here: https://github.com/Shopify/constant_resolver/issues/26. My ideal for this would be sorbet of course, but there may be some separate challenges to make that happen.

Let me know what you're all thinking about this!

**Comment by AlexEvanczuk** [comment]
Thanks for making that distinction more clear @exterm 

I think that makes sense. To reiterate what we chatted about over video call, I think that moving to a faster parser should give us a lot of wiggle room to move to a thread-based approach to address this memory issue more simply.

**Comment by rafaelfranca** [comment]
Rails is very good with copy-and-write, that is how puma and unicorn work in production without each process having the entire Rails application in resident memory, so if we boot the application in the master process, before we fork the other processes, the resident memory of each one of those process would be only for the new allocated or modified memory.

**Comment by alexevanczuk** [comment]
Hi @fhwang I believe we've discovered (per Rafael's comment) that this is not an issue because Rails is good at being able to reuse memory space for forked processes.

I'm going to close this for now! Please leave a comment or reopen if you or anyone sees more issues.
