### ISSUE TITLE
[Bug Report] Dependency violation not flagged when Zeitwerk collapsing is used

### ISSUE THREAD

**Issue by pareeohnos** [Shopify/packwerk#406]
**Description**
A package calling another package is not triggering a violation

**To Reproduce**
- Create `app/modules` folder
- Create two packages in the new folder, with `package.yml` files enforcing dependencies
- Add a class in each package. Make one call the other
- Run `bin/packwerk check`

**Expected Behaviour**
A violation error to be raised

**Screenshots**
I've created a reproduction of the issue here https://github.com/pareeohnos/packwerk-issue

**Version Information**
 - Packwerk: 3.2
 - Ruby 3.3.0

**Additional Context**
The project structure contains modules in the `app/modules` directory. Within each package, each sub-directory is collapsed in Zeitwerk, so for example the directory `app/modules/package_one/services/service_one.rb` is loaded its `PackageOne::ServiceOne` instead of `PackageOne::Services::ServiceOne`.

I've tried removing the dependency on `.` and it triggers violations, but this is because the `ApplicationController` and `ApplicationRecord` classes are both located in the root of the project - it still makes not mention of the cross package violation.

If I remove the collapsing altogether, it starts to work correctly but this causes issues in our application so we need the collapsing.

**Comment by fxn** [comment]
Packwerk uses its own constants resolver.

The last version of Zeitwerk provides [Zeitwerk::Loader#all_expected_cpaths](https://github.com/fxn/zeitwerk?tab=readme-ov-file#zeitwerkloaderall_expected_cpaths) that could help Packwerk honor user configuration like that by delegating that resolution to the Rails autoloaders.

**Comment by Catsuko** [comment]
This is acknowledged in the [README](https://github.com/Shopify/packwerk?tab=readme-ov-file#limitations):
>Support for custom Zeitwerk configuration is limited. If [custom ActiveSupport inflections](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#customizing-inflections) are used, Packwerk will understand that and everything is fine. However, if Zeitwerk is directly configured with [custom Zeitwerk inflections](https://github.com/fxn/zeitwerk#inflection) or to [collapse directories](https://github.com/fxn/zeitwerk#collapsing-directories), Packwerk will get confused and produce false positives.

I also hit this while trying to get a similar namespace to the one you mentioned 😭 Although I ended up giving up, while investigating I came across [this gem](https://github.com/gap777/automatic_namespaces) which might be of interest to you.

**Comment by pareeohnos** [comment]
@Catsuko yeah I found that snippet yesterday afternoon :( I'll take a look at that other gem though thanks

**Comment by gmcgibbon** [comment]
Indeed the issue is:
```
Dir[Rails.root.join('app/modules/{*/*/}')].each do |dir|
  Rails.autoloaders.main.collapse(dir)
end
```
[Constant resolver ](https://github.com/Shopify/constant_resolver)is what we use to map constants to files, and unfortunately I don't think we want to support this use-case. `Rails.autoloaders` is actually private API, so you arguably shouldn't be fighting with the frameworks' autoloading conventions. I would suggest using Rails [engines](https://guides.rubyonrails.org/engines.html#generating-an-engine) to define package boundaries instead of your current setup with custom nesting. Since there's nothing to do here, I'm closing this for now.

**Comment by Catsuko** [comment]
>It seems to me that all_expected_cpaths should be considered as a path forward - I'm just not sure there's anyone right now interested in doing this refactor.

I am interested since I really want to use collapse however I don't quite understand how you would use `all_expected_cpaths` 🤔 

My understanding from this thread is that when [finding paths for constants](https://github.com/Shopify/packwerk/blob/main/lib/packwerk/constant_discovery.rb#L58-L73), rather than using `ConstantResolver` we would use Zeitwerk instead. So would you invert the `all_expected_cpaths` map and then use that to map from the constant name to the expected path?

**Comment by fxn** [comment]
The natural map is from file system path to constant path. Because the file system is the input, from there, you compute the expected constant path at the spot. You cannot go from constant path to file system.

If you invert, take into account namespaces may be spread in multiple directories and, in the case of explicit ones, a Ruby file. So, inverting the map would need to account for collections.

There is also the edge case of [shadowed files](https://github.com/fxn/zeitwerk?tab=readme-ov-file#shadowed-files). They can also produce collections for files that are not necessarily namespaces.

**Comment by fxn** [comment]
I read that code a while back and could be mistaken, but I think that only deals with files with ".rb" extension. That is different (addresses shadowed files, I believe).

But, if Packwerk does not deal with namespace ownership, then directory entries can be ignored.

**Comment by Catsuko** [comment]
@fxn 
I made a proof of concept [here](https://github.com/Shopify/packwerk/pull/410), here you can see my use of [all_expected_cpaths](https://github.com/Shopify/packwerk/pull/410/commits/ff62ac18e90d50f4e63ea81027b0897f3aecc559#diff-8aa9e8fd4e164114f7d838b524d6e4edaf76a68f05dc4b9996fd5de8944a74e3R80-R93). It is passing all tests (with some setup changes) and also working for me on my repo.

If you had any time to take a look, I'd be eager to hear if this lines up with what you were thinking 🤔
